defaults:
  - redis: local
  - streams: sensors
  - _self_

output: recording.msgpack
from_beginning: false
rotate_key: null
batch_size: 100
max_duration: ${oc.env:RECORD_MAX_DURATION,null}
max_size_mb: ${oc.env:RECORD_MAX_SIZE_MB,null}
verbose: false
